### ISSUE TITLE
Usage with e3kit?

### ISSUE THREAD

**Issue by hellogerard** [VirgilSecurity/react-native-virgil-crypto#1]
Thanks, this package looks great. I am currently using Virgil via e3kit (https://github.com/VirgilSecurity/virgil-e3kit-js). Is there an easy way to swap this package in for use with e3kit?

**Comment by vadimavdeev** [comment]
Unfortunately, this library cannot be swapped in in e3kit currently for two reasons: first, e3kit bundles the JS library, and second, e3kit uses a feature that this library does not currently have - `VirgilPythiaCrypto` used for creating encrypted private key backups.

We will make this library available for use with e3kit, but I cannot estimate when that will happen as of yet. We'll keep this issue open for further discussion and updates. Thanks

**Comment by hellogerard** [comment]
Thanks for the response. We are about to release our app to production using the standard e3kit flow. It is working fine, but it's a bit slow. I'd like to learn more about the challenges here. As far as e3kit bundling the JS library, I think we could work thru that by creating our own "e3kit." But I don't quite understand this

> e3kit uses a feature that this library does not currently have - VirgilPythiaCrypto 

What exactly does VirgilPythiaCrypto do? Is it for generating the actual keypair or for backing up the private key (I thought that's what Keyknox was for)? Is it optional?  Would it be possible to integrate [virgil-pythia-x](https://github.com/VirgilSecurity/virgil-pythia-x) and [virgil-pythia-java](https://github.com/VirgilSecurity/virgil-pythia-java) somehow to create a  `react-native-e3kit`?  

Sorry for the questions. Just trying to understand how the myriad pieces fit together.

**Comment by vadimavdeev** [comment]
Both VirgilPythiaCrypto and Keyknox are used for backing up the private key. VirgilPythiaCrypto creates a key pair out of the backup password to encrypt the value that is then stored in Keyknox. It is not optional, unless you create your own "e3kit" without key backups. 

We're currently working on adding VirgilPythiaCrypto and features required by Keyknox to this library. You can follow our progress in the [e3kit-compat](https://github.com/VirgilSecurity/react-native-virgil-crypto/tree/e3kit-compat) branch. The release is planned for next week. Then we'll need to update e3kit to allow to swap this library in for js virgil-crypto. It shouldn't take too long, but I can't give the exact timing as of now.

**Comment by hellogerard** [comment]
> VirgilPythiaCrypto creates a key pair out of the backup password to encrypt the value that is then stored in Keyknox

Ah, ok. Got it. That makes sense. Curious, if Pythia is only needed for backup operations, would it be possible to do the actual encrypt/decrypt natively, and keep the backup operations in Javascript?  Asking out of curiosity, because if your next paragraph is true...

> We're currently working on adding VirgilPythiaCrypto and features required by Keyknox to this library.

Great news! I will keep an eye on this thread closely. In looking at [virgil-e3kit-x](https://github.com/VirgilSecurity/virgil-e3kit-x), it seems like all the pieces are there, now just to put them together for consumption by React Native...

**Comment by hellogerard** [comment]
Meant to ask one important question: will the new library be able to decrypt messages that were  encrypted by the current JS-backed e3kit?  I am guessing the answer is yes, since the fundamental algorithm remains the same.

**Comment by vadimavdeev** [comment]
Yes, this library will be able to decrypt messages encrypted by js library. As for the previous question, it is possible to keep backup operations in js, but those will have the same problem that made us create this library - the lack of secure PRNG.

**Comment by vadimavdeev** [comment]
Please check out the beta release of E3kit with ability to [use this library](https://github.com/VirgilSecurity/virgil-e3kit-js/#react-native-usage) in React Native! 
I'm closing this. Feel free to open new issues if you encounter any problems in integration with E3kit.

**Comment by hellogerard** [comment]
> import { EThree } from '@virgilsecurity/e3kit/native';

That's it?! Awesome! I will start looking at this right away.
