### ISSUE TITLE
Can't see Register and Initialize of E3

### ISSUE THREAD

**Issue by hirokimoto** [VirgilSecurity/react-native-virgil-crypto#12]
Hi VirgilSecurity Team,

I am new to one this library for React Native and can't see the following functions of E3.

https://share.getcloudapp.com/lluwnvBX

You guys know, E3 supports those 2 functions and I think we must need to use that in React Native, too.
But I think this library still does not support those 2 functions.

Am I missing something?

**Comment by vadimavdeev** [comment]
Hello,
This library is not E3kit for React Native, it's crypto library that E3kit uses in React Native. The actual E3kit package with `EThree` class that has all of the methods from our docs can be found in its own repository here - https://github.com/VirgilSecurity/virgil-e3kit-js
