### ISSUE TITLE
Unable to decrypt locally stored encrypted image.

### ISSUE THREAD

**Issue by mahesh-saal** [VirgilSecurity/react-native-virgil-crypto#13]
Hi, I used virgilCrypto for encrypting my captured image & able to do encryption on that. This file I stored in my apps document directory. Now problem I am facing is I am not able to decrypt image. 
This is my code to encrypt Image which gives encrypted image of 700Kb 
 
```
const keypair = virgilCrypto.generateKeys();
var destPath = RNFS.DocumentDirectoryPath + `/${rawData.scan_id}.jpg`;
const encryptedFilePath = await virgilCrypto.encryptFile({
inputPath: this.props.navigation.getParam('picturePath'), 
outputPath: destPath,
publicKeys: keypair.publicKey
})
```

And this is to decrypt image which gives dencrypted image of 0Kb 

        let imagePath1 = RNFS.DocumentDirectoryPath +`/${scanId}.jpg`;
        const keypair = virgilCrypto.generateKeys();
        virgilCrypto.decryptFile({
            inputPath: imagePath1, 
            outputPath: undefined,
            privateKey:keypair.privateKey  // I tried with saved pubilc and private key of above encrypted image  
          }).then (decryptedFilePath => {
            this.setState({
                imagePath:decryptedFilePath
            })
        })

Please help me where I am doing wrong.

**Comment by vadimavdeev** [comment]
Hello,

The code looks fine, except that when decrypting, you need to get the key pair you used for encryption, like it says in the comment in your code snippet. 

Just to clarify, do you get any errors during decryption or does it just return a path to an empty file? Which versions of `react-native`, `react-native-fs` and `react-native-virgil-crypto` do you have? And where did you test this (Android, iOS, both)?

**Comment by mahesh-saal** [comment]
I tried on Android first. I used device file explorer of android studio, here I can see encrypted Image, and I can see empty file created with no errors. And I tried with the encrypted keypair still I am getting empty file. 

"react-native-fs": "^2.14.1",
"react-native": "0.59.9",
"react-native-virgil-crypto": "^0.3.2",

**Comment by vadimavdeev** [comment]
I tried running our [sample project](https://github.com/VirgilSecurity/react-native-virgil-crypto/tree/master/examples/FileEncryptionSample) and it worked fine. Can you check it out and see if you do something differently? Also, it would help if you could step through the [decryptFile](https://github.com/VirgilSecurity/react-native-virgil-crypto/blob/6586784eb6bb98b6625a26f44bbaaf5e392072f4/android/src/main/java/com/virgilsecurity/rn/crypto/RNVirgilCryptoModule.java#L365) function with a [native debugger](https://github.com/VirgilSecurity/react-native-virgil-crypto/tree/master/examples/FileEncryptionSample) attached and see if it ends successfully.

**Comment by mahesh-saal** [comment]
It is working now, maybe somewhere imagePath and keypair was not matching. So I tried with this and it is giving very accurate expected result. Now I can split this code as per my requirements. 
Thanks a lot for the help. Hope below code will help someone. 

```
virgilCrypto.encryptFile({
      inputPath: this.props.navigation.getParam('picturePath'), 
      outputPath: undefined,
      publicKeys: keypair.publicKey
    })
    .then(encryptedFilePath=>{
      virgilCrypto.decryptFile({
        inputPath: encryptedFilePath,
        outputPath: undefined,
        privateKey: keypair.privateKey,
      })
    })
```
