### ISSUE TITLE
Private key gets modified/expired after reopening app.

### ISSUE THREAD

**Issue by mahesh-saal** [VirgilSecurity/react-native-virgil-crypto#17]
Hi, 
I have my successfully working flow like this -> 
1) I capture image -> able to encrypt & store in documents directory of app.
2) While encrypting Image , I store keypair in **Redux-Persist**.
3) For decrypting image I fetch that stored keypair from **Redux-Persist** -> able to decrypt image -> show that image to user -> while navigating back I delete that decrypted Image. (Client Requirement not to store decrypted image). I can do this step many times before closing app.
4) Now when I close app & reopen again -> try to decrypt image , here I am not able to decrypt image, getting error **Argument 'virgilPrivateKey' is not 'virgilPrivateKey'**. 
5) All other states are maintained from redux persist but not this private key. I suspect this private key gets modified.

Please help me for this.

**Comment by vadimavdeev** [comment]
Hi! Please make sure that the key is serialized before it gets persisted: 
```javascript
const valueToPersist = virgilCrypto.exportPrivateKey(yourKey).toString('base64');
```
And de-serialized before it's rehydrated:
```javascript
const privateKey = virgilCrypto.importPrivateKey(persistedValue);
```
