### ISSUE TITLE
virgilCrypto-swift.h not found.

### ISSUE THREAD

**Issue by mahesh-saal** [VirgilSecurity/react-native-virgil-crypto#18]
Hi, I am facing this issue while building ios app. React-native-virgil-cryto successfully worked for android, now I am tying for ios. I tried with cocoapods & carthage both. Still I am facing this issue.  I have react & react-native versions "16.8.3" &   "0.59.9" respectively. And for React-native-virgil-cryto "^0.3.2" & tried with latest version also.

**Comment by vadimavdeev** [comment]
Hi! What is the error that you're getting? Did you follow the instructions in [README](https://github.com/VirgilSecurity/react-native-virgil-crypto#ios-setup)? Please see the section beginning with **RN<60** if you use CocoaPods.
To recap, you need:

```sh
npm i react-native-virgil-crypto
react-native link react-native-virgil-crypto
```

Then, add the following lines into `ios/Podfile`:

```ruby
target 'YOUR_APP_NAME' do
  use_frameworks!
  
  # your existing pods

  pod 'VirgilCrypto', '~> 5.2.0'
  pod 'VirgilCryptoFoundation', '~> 0.11.0'
  pod 'VirgilCryptoPythia', '~> 0.11.0'
```

And finally, run `pod install` in the `ios` directory.

If you tried both CocoaPods and Carthage, make sure you clean up (i.e. undo everything you did) before trying again. Also, please see [this issue](https://github.com/VirgilSecurity/react-native-virgil-crypto/issues/5), it might be related.

**Comment by mahesh-saal** [comment]
Hi, 
Pods did not work for me , carthage worked after reconfiguring project.

**Comment by vadimavdeev** [comment]
It seems like the issue is resolved, so I'm closing this. Feel free to reopen if the problem appears again.

**Comment by tian-chaiyaporn** [comment]
@vadimavdeev 

Hi, so I have a similar problem but with VirgilCrypto version 5.2.0

My error is this: "VirgilCrypto.h" file not found

I managed to track down the problem to the fact that react-native-virgil-crypto is importing this file that exists in virgil-crypto-x version 3.2.3 but not in version 5.2.0

Can you please check if this is the case.

**Comment by tian-chaiyaporn** [comment]
Hi @snanovskyi  any progress on this? Just wanted to know if it's being worked on, so I can find alternative solutions if otherwise - thank you

**Comment by snanovskyi** [comment]
Hi @tian-chaiyaporn 👋

I'm currently working on update for the library which will be hopefully released later today. It will contain pre-configured projects that can be used as reference for your own projects (for React Native 0.59.x and 0.61.x).

Imho, it's better to use only one dependency manager(for React Native it is CocoaPods). Using Carthage and manual configuration is a workaround for 0.60.x due to [compatibility issue](https://github.com/facebook/react-native/issues/25349) with `use_frameworks!`. Also it is quite tricky in my opinion.
If this is your case, I highly suggest you to avoid 0.60.x and to upgrade to 0.61.x.

I'll let you know when new version of the library will be available.

**Comment by tian-chaiyaporn** [comment]
@snanovskyi  ok, thanks you, and for the advice too. I appreciate it. I'm sort of stuck in RN 0.59 due to another library the app is depended on, but I will try it either way, and update it to 0.61 if all else fails.

Thanks again

**Comment by snanovskyi** [comment]
@tian-chaiyaporn we published new version of the library 🚀

Here is our [0.59.x example](https://github.com/VirgilSecurity/react-native-virgil-crypto/tree/master/examples/Example59). Also have a look at [this article](https://engineering.brigad.co/demystifying-react-native-modules-linking-ae6c017a6b4a). It might help.

Let me know if you need some help 🙂

**Comment by tian-chaiyaporn** [comment]
Perfect. Thanks so much @snanovskyi

**Comment by Beaudinn** [comment]
Hi!,

I have the same issue using react native version 0.61.4  react-native-virgil-crypto and 0.5.0.
My error is this: "VirgilCrypto.h" file not found
I've looked at 0.61.x example I think I have everything set up properly.

**Comment by snanovskyi** [comment]
Hi @Beaudinn !
```
'VirgilCrypto/VirgilCrypto-Swift.h' file not found
'VirgilCryptoFoundation/VirgilCryptoFoundation-Swift.h' file not found
'VirgilCryptoPythia/VirgilCryptoPythia-Swift.h' file not found
```
These errors mean that you don't have `use_frameworks!` in your Podfile.
You need to add `use_frameworks!` and then run `pod install`.
You also might need to remove `Pods`, `Podfile.lock` and `build` in your `/ios` directory.

**Comment by snanovskyi** [comment]
If you still need help setting up your project you can jour our [Slack community](https://virgilsecurity.com/join-community) and get in touch with our team there.
