### ISSUE TITLE
Using This Library Without 'use_frameworks!', RN 0.61.4

### ISSUE THREAD

**Issue by rantwijk** [VirgilSecurity/react-native-virgil-crypto#19]
Hello,

I've been spending the day trying to make this library compile correctly within my RN project. I'm using RN 0.61.4 (upgraded in order to support auto-linking) and cocoapods 1.8.4.

In the README, I see the following:

> RN>0.61
With React Native > 0.61 linking is done automatically. You just need to make sure you have use_frameworks! in your Podfile and you run pod install inside the ios folder after installing from npm.

However, when adding the "use_frameworks!" line to my Podfile, Firebase fails to compile. Removing Firebase results in others failing as well. 

I'd rather avoid using "use_frameworks!" and still use this library in RN 0.61.4. Is there a way to accomplish this?

I had the idea to try to use ":modular_headers => true" in the Podfile, but since this library is auto-linked I'm not able to do so.

Thanks!

**Comment by snanovskyi** [comment]
Under the hood this library uses [virgil-crypto-x](https://github.com/VirgilSecurity/virgil-crypto-x) and, as far as I know, it's not possible to use it without `use_frameworks!` in CocoaPods.

**Comment by snanovskyi** [comment]
So I took a deeper look at this issue 🙂

https://invertase.io/oss/react-native-firebase/releases/v6.0.0#changelog
> Note: Currently this has been disabled as use_frameworks! support in React Native was broken again in RN60. We'll re-enable in a future release for RN61.

I tried to use `@react-native-firebase/app@6.3.2` locally and they haven't enabled `use_frameworks!` yet... Meanwhile React Native already has 0.62.0-rc.2 and multiple 0.61.x releases.

Here is a workaround for you, until they release a proper update:
1. Open `node_modules/@react-native-firebase/app/RNFBApp.podspec`
2. Change `s.static_framework = false` to `s.static_framework = true`
3. `cd ios && pod install`
4. Run the app

The workaround is based on [this comment](https://github.com/invertase/react-native-firebase/issues/2599#issuecomment-533109149) and can be used to fix all RNFirebase packages.

**Comment by snanovskyi** [comment]
If you still need help setting up your project you can jour our [Slack community](https://virgilsecurity.com/join-community) and get in touch with our team there.
