### ISSUE TITLE
'VirgilCrypto/VirgilCrypto-Swift.h' file not found

### ISSUE THREAD

**Issue by aomari** [VirgilSecurity/react-native-virgil-crypto#32]
I have tried to install this library and got this error 
**'VirgilCrypto/VirgilCrypto-Swift.h' file not found**

steps to reproduce:

1. yarn add react-native-virgil-crypto
2. cd ios/ &&  pod install && cd ..
3. open Xcode.
4. compile the code. 

react-native and npm used versions:
1. react-native-cli: 2.0.1
2. react-native: 0.60.6
3. npm: 6.13.4

**Comment by xlwknx** [comment]
Hi, @aomari 
React 0.60.x is not supported due to [compatibility issue](https://github.com/facebook/react-native/issues/25349) with `use_frameworks!` 

You can find related docs here:
https://github.com/VirgilSecurity/react-native-virgil-crypto#install

**Comment by desinl** [comment]
hi, we are having the same issue. 
RN 0.58

can someone help? thanks.

**Comment by rohitsainiidsil** [comment]
Facing same problem with RN 0.63.2. Any solution ?

**Comment by juanEdukathe** [comment]
Facing the same problem with RN 0.63.4. Any solution?
