### ISSUE TITLE
[iOS] Manual installation causes building error + [Android] Build fails due to minSdkVersion

### ISSUE THREAD

**Issue by paolospag** [VirgilSecurity/react-native-virgil-crypto#8]
Hi! 
I'm experiencing some problems due to manual installation.
I followed these steps:
> 1. In XCode, in the project navigator, right click `Libraries` ➜ `Add Files to [your project's name]` 
> 2. Go to `node_modules` ➜ `react-native-virgil-crypto` and add `RNVirgilCrypto.xcodeproj` 
> 3. In XCode, in the project navigator, select your project. Add `libRNVirgilCrypto.a` to your project's `Build Phases` ➜ `Link Binary With Libraries`

but when I run the `react-native run-ios --simulator="iPhone 8"` command the build fails with the following error:
```
// OTHER ERRORS HERE
...
fatal error: could not build module 'Darwin'
#include <TargetConditionals.h>
 ~~~~~~~~^
...
fatal error: could not build module 'CoreFoundation'
#include <CoreFoundation/CoreFoundation.h>
 ~~~~~~~~^
...
fatal error: could not build module 'Foundation'
#include <Foundation/Foundation.h>
 ~~~~~~~~^
...
fatal error: could not build module 'QuartzCore'
#import <QuartzCore/QuartzCore.h>
 ~~~~~~~^
** BUILD FAILED **


The following build commands failed:
        CompileC /MY/APP/PATH/Build/Intermediates.noindex/RNVirgilCrypto.build/Debug-iphonesimulator/RNVirgilCrypto.build/Objects-normal/x86_64/ResponseFactory.o
/MY/APP/PATH/node_modules/react-native-virgil-crypto/ios/ResponseFactory.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
```

I tried to set Header Search Path in Build Setting like that:
```
$(SRCROOT)/../node_modules/react-native-virgil-crypto/ios            non-recursive
```

But the build fails anyway.

Are other manual installation steps required? 🤔

**UPDATE (2019-09-23)**

I didn't see this recommendation in the documentation:
> The recommended option is to install the native dependency with Carthage and link the bridge (i.e. this library) manually.

build probably fails due to native dependencies missing, but I've never used Carthage.
Is there an alternative to integrate native dependencies?

**Comment by paolospag** [comment]
The build fails even on Android due to the minimum version of the SDK with the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugManifest'.
> Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 21 declared in library [com.virgilsecurity.crypto:pythia-android:0.10.0] /Users/apple/.gradle/caches/transforms-2/files-2.1/d8c3ea03b106e704d30f97a4fe4d405f/AndroidManifest.xml as the library might be using APIs not available in 16
        Suggestion: use a compatible library with a minSdk of at most 16,
                or increase this project's minSdk version to at least 21,
                or use tools:overrideLibrary="com.virgilsecurity.crypto.pythia" to force usage (may lead to runtime failures)
```

My app needs to stay on `minSdkVersion:16`, what can I do to resolve that?

**Comment by vadimavdeev** [comment]
Alternative way to install native dependencies on iOS would be to install them using CocoaPods, but it will not work with React Native 0.60.x due to incompatibility with `use_framweorks!` mentioned in Readme. If you have React Native 0.59.x or less, you can add the following lines to your `Podfile`:

```
use_frameworks!

pod 'VirgilCrypto', '5.1.0'
pod 'VirgilCryptoFoundation', '~> 0.10.0'
pod 'VirgilCryptoPythia', '~> 0.10.0'
```
and then do `pod install`

As for the Android min SDK version, I'm afraid it's a requirement of the [underlying crypto library](https://github.com/VirgilSecurity/virgil-sdk-java-android) and there's nothing we can do about it on this library's side

**Comment by paolospag** [comment]
**iOS**
unfortunately, I'm already using the `0.60.x` version and at this point I'll have to wait for the new version of `react-native`.

**Android**
why the underlying crypto library `minSdkVersion` is `21`? API incompatibility? 
Do you expect to release a version compatible with at least `minSdkVersion:19` in the future?

All this makes the integration process difficult...

**Comment by paolospag** [comment]
@vadimavdeev 
In the meantime, I tried to follow the steps for installing native dependencies through Carthage but build fails anyway.

![Schermata-2019-09-24-alle-13 42 04](https://user-images.githubusercontent.com/35046292/65509106-003ce500-ded2-11e9-9519-759e5eb758ba.jpg)

As you can see from the screenshot, 
- I imported the frameworks along with `libRNVirgilCrypto.a`
- I created a "New Run Script Phase" and listed the "Input files"

but I'm not able to build with this configuration:

```
"@virgilsecurity/key-storage-rn": "^0.2.0-alpha.0",
"react-native": "0.60.5",
"react-native-virgil-crypto": "0.3.0",
"virgil-sdk": "^6.0.0-alpha.1"
```

**Comment by vadimavdeev** [comment]
@paolospag Do you have any `'VirgilCrypto'`  pods in your Podfile? If so try removing them and running `pod install` again. You can also try to [clean Derived Data](https://iosdevcenters.blogspot.com/2015/12/how-to-delete-derived-data-and-clean.html) in XCode. If that doesn't help, another possible solution would be to remove all of the dependencies (i.e. `node_modules`, `ios/Pods` and `ios/Carthage` folders) and install them again.

**Comment by vadimavdeev** [comment]
@paolospag please check if removing `$(SRCROOT)/../../../ios/Pods/Headers` line in HEADER_SEARCH_PATHS of the `RNVirgilCrypto.xcodeproj` fixes the problem

<img width="1420" alt="Screenshot 2019-09-24 17 12 41" src="https://user-images.githubusercontent.com/2556129/65519580-d1813780-deee-11e9-8563-1ba21a479f3a.png">

**Comment by paolospag** [comment]
@vadimavdeev with your suggestion I reduce the amount of errors to one

![Schermata 2019-09-24 alle 16 44 33](https://user-images.githubusercontent.com/35046292/65522196-b280a680-deea-11e9-90c2-6f44532eb18c.png)

but build fails anyway...

**Comment by vadimavdeev** [comment]
@paolospag could you create a sample project and share it with me so I can debug it locally? If not, I'll need at least your `package.json`, `ios/Podfile`, `ios/Cartfile` and `<YOUR_APP>.xcodeproj` files, and the output of `react-native info` command

**Comment by vadimavdeev** [comment]
@paolospag actually, just making sure that `HEADER_SEARCH_PATHS` in your project Build Settings do not include any recursive entries under the Pods directory may fix the issue. It should look like this 

<img width="1424" alt="Screenshot 2019-09-24 18 49 21" src="https://user-images.githubusercontent.com/2556129/65527858-0e076000-defc-11e9-83ee-24bc744199b2.png">

See [this comment](https://github.com/firebase/firebase-ios-sdk/issues/1916#issuecomment-474153045) in a similar issue in firebase-ios-sdk.

Note that you'll need to revert the [workaround](https://github.com/VirgilSecurity/react-native-virgil-crypto/issues/8#issuecomment-534578933) that I suggested earlier

**Comment by paolospag** [comment]
@vadimavdeev I have a simular situation, I don't include any recursive entries

![Schermata 2019-09-24 alle 18 09 49](https://user-images.githubusercontent.com/35046292/65529543-9b47b600-def6-11e9-826e-a2f064465f1a.png)
![Schermata 2019-09-24 alle 18 10 07](https://user-images.githubusercontent.com/35046292/65529545-9b47b600-def6-11e9-8746-a4c17dadd400.png)
![Schermata 2019-09-24 alle 18 10 23](https://user-images.githubusercontent.com/35046292/65529547-9be04c80-def6-11e9-8053-33ebf0ee1dcc.png)

but at the `RNVirgilCrypto.xcodeproj` level, switch from recursive to non-recursive could solve the problem?

**Comment by vadimavdeev** [comment]
@paolospag yes, I think changing `$(SRCROOT)/../../../ios/Pods/Headers` `recursive` to `$(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core` `non-recursive` at the RNVirgilCrypto.xcodeproj level can fix the problem.

**Comment by paolospag** [comment]
@vadimavdeev 
so, if I understand, at `RNVirgilCrypto.xcodeproj` level I should replace this recursive entry:
![Schermata-2019-09-25-alle-12 14 54](https://user-images.githubusercontent.com/35046292/65592138-48b9d880-df8e-11e9-9e0d-464b9a93d2b0.jpg)

with these two non-recursive entries:
```
$(SRCROOT)/../../../ios/Pods/Headers/Public
$(SRCROOT)/../../../ios/Pods/Headers/Public/React-Core
```

Correct?

P.S. `react-native@0.61` is out, when are you planning to release an update with CocoaPods support?

**Comment by vadimavdeev** [comment]
Great news. Glad it solved the issue. We'll start working on CocoaPods support in a week or two. We're in the middle of adding group encryption capability into [E3kit].(https://github.com/VirgilSecurity/virgil-e3kit-js)
